
export default{
    setTableName(state,name){//对应表格名称
        state.tableName=name;
    },
    setQueryParams(state,params){//查询请求参数
        state[state.tableName+'QueryParams']=params;
    },
    Init_Table(state,data){//表格数据模型
        state[state.tableName+'Table']=data;
    },
    Init_TableClone(state,data){
        state[state.tableName+'TableClone']=data;
    },
    setQueryApi(state,api){//查询api地址
        state[state.tableName+'QueryApi']=api;
    },
    tableLoad_Complete(state,data){//加载动画
        state[state.tableName+'Loading']=data;
    },
    Init_pagination(state,data){//页码总数
        state[state.tableName+'TotalPagination']=data
    },
    Init_TotalCount(state,data){//总条数
        state[state.tableName+'TotalCount']=data
    },
    setCurrentPage(state,page){//当前页码
        state[state.tableName+'CurrentPage']=page;
    },
    setEachPage(state,page){//设置每页显示条数
        state[state.tableName+'EachPage']=page;
    },
    setAddColArray(state,array){//重置行内新增集合
        state[state.tableName+'NewColArray']=array;
    },
    setUpdateColArray(state,array){//重置行内修改集合
        state[state.tableName+'UpdateColArray']=array;
    },
    setTableSelection(state,array){//设置表格多选集合
        state[state.tableName+'Selection']=array;
    },
    add_col(state,data){//表格行内新增
        state[state.tableName+'Table'].unshift(data);
        state[state.tableName+'NewColArray'].unshift(data);
    },
    Add_UpdateArray(state,data){//行内修改集合
        state[state.tableName+'UpdateColArray'].push(data);
    },
    get_RowId(state,data){//行id
        state[state.tableName+'UpdateRowId']=data;
    },
}